CREATE DATABASE IF NOT EXISTS artvault_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE artvault_db;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role ENUM('visitor','artist','curator','admin') NOT NULL DEFAULT 'visitor',bio TEXT,avatar_url VARCHAR(500),is_verified BOOLEAN DEFAULT TRUE,is_active BOOLEAN DEFAULT TRUE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE artworks (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,description TEXT,category VARCHAR(100),medium VARCHAR(100),year INT,price DECIMAL(12,2) NOT NULL DEFAULT 0,image_url VARCHAR(500) NOT NULL,status ENUM('draft','published','sold','archived') DEFAULT 'published',views INT DEFAULT 0,artist_id INT NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(artist_id) REFERENCES users(id));
CREATE TABLE exhibitions (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(180) UNIQUE NOT NULL,description TEXT,banner_url VARCHAR(500),starts_at DATETIME,ends_at DATETIME,curator_id INT NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(curator_id) REFERENCES users(id));
CREATE TABLE exhibition_artworks (exhibition_id INT,artwork_id INT,PRIMARY KEY(exhibition_id,artwork_id),FOREIGN KEY(exhibition_id) REFERENCES exhibitions(id),FOREIGN KEY(artwork_id) REFERENCES artworks(id));
CREATE TABLE wishlists (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,artwork_id INT NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE(user_id,artwork_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(artwork_id) REFERENCES artworks(id));
CREATE TABLE follows (id INT AUTO_INCREMENT PRIMARY KEY,follower_id INT NOT NULL,artist_id INT NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE(follower_id,artist_id),FOREIGN KEY(follower_id) REFERENCES users(id),FOREIGN KEY(artist_id) REFERENCES users(id));
CREATE TABLE reviews (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,artwork_id INT NOT NULL,rating INT NOT NULL,comment TEXT,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE(user_id,artwork_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(artwork_id) REFERENCES artworks(id));
CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,status ENUM('pending','paid','shipped','delivered','cancelled') DEFAULT 'pending',total_amount DECIMAL(12,2) NOT NULL,shipping_address TEXT NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE order_items (id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,artwork_id INT NOT NULL,product_type ENUM('digital','canvas','print','frame','poster','merchandise') NOT NULL,quantity INT DEFAULT 1,unit_price DECIMAL(12,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(artwork_id) REFERENCES artworks(id));
CREATE TABLE notifications (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,is_read BOOLEAN DEFAULT FALSE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE coupons (id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) UNIQUE NOT NULL,discount_percent INT NOT NULL,is_active BOOLEAN DEFAULT TRUE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
